export const projects = [
  {
    id: "fitness-gym-app",
    title: "Fitness & Gym app",
    path: "/fitness-gym-app",
    label: "Body systems",
    tone: "High voltage discipline",
    prompt: "prompt here",
  },
  {
    id: "restaurant-food",
    title: "Restaurant & Food",
    path: "/restaurant-food",
    label: "Hospitality",
    tone: "Warm appetite theater",
    prompt: "prompt here",
  },
  {
    id: "real-estate",
    title: "Meridian Quarter",
    path: "/real-estate",
    label: "Mixed-use district",
    tone: "Cinematic site walk",
    prompt:
      "Build a scroll-experience page for Meridian Quarter, a 14-acre mixed-use development launching in Austin in 2027.",
  },
  {
    id: "health-wellness",
    title: "Health & Wellness",
    path: "/health-wellness",
    label: "Care",
    tone: "Calm proof and softness",
    prompt: "prompt here",
  },
  {
    id: "fintech-crypto-dashboard",
    title: "Fintech crypto dashboard",
    path: "/fintech-crypto-dashboard",
    label: "Capital",
    tone: "Risk, signal, velocity",
    prompt: "prompt here",
  },
  {
    id: "saas-analytics-dashboard",
    title: "SaaS Analytics Dashboard",
    path: "/saas-analytics-dashboard",
    label: "Operations",
    tone: "Executive data command",
    prompt: "prompt here",
  },
  {
    id: "educational-platform",
    title: "Educational platform",
    path: "/educational-platform",
    label: "Learning",
    tone: "Momentum through mastery",
    prompt: "prompt here",
  },
  {
    id: "pet-grooming-spa",
    title: "Pet grooming & Spa",
    path: "/pet-grooming-spa",
    label: "Local service",
    tone: "Tender detail and trust",
    prompt: "prompt here",
  },
  {
    id: "ai-chatbot-platform",
    title: "AI chatbot platform",
    path: "/ai-chatbot-platform",
    label: "AI product",
    tone: "Conversation as interface",
    prompt: "prompt here",
  },
];
